# Generated by Django 4.1.1 on 2022-09-21 09:23

import django.core.validators
from django.db import migrations, models
import my_music_app.web_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), my_music_app.web_app.models.validate_username]),
        ),
    ]
